// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhLAhLrGL9JGhXqUUthu_qKntOcM3j_k',
    appId: '1:282526496692:web:c916311486ce26a93ba4e1',
    messagingSenderId: '282526496692',
    projectId: 'fashion-4dbac',
    authDomain: 'fashion-4dbac.firebaseapp.com',
    storageBucket: 'fashion-4dbac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TVS6-LhGSt2sKL6pfvtCuRkpfrc5qYk',
    appId: '1:282526496692:android:7a3c106c2eaf7cb53ba4e1',
    messagingSenderId: '282526496692',
    projectId: 'fashion-4dbac',
    storageBucket: 'fashion-4dbac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW5_oGdH7oEPRNYhxXKXYLCKhfA3Xvixc',
    appId: '1:282526496692:ios:204d06ceabf31cfd3ba4e1',
    messagingSenderId: '282526496692',
    projectId: 'fashion-4dbac',
    storageBucket: 'fashion-4dbac.appspot.com',
    iosBundleId: 'com.example.fashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW5_oGdH7oEPRNYhxXKXYLCKhfA3Xvixc',
    appId: '1:282526496692:ios:28b7bfbef1a1b2883ba4e1',
    messagingSenderId: '282526496692',
    projectId: 'fashion-4dbac',
    storageBucket: 'fashion-4dbac.appspot.com',
    iosBundleId: 'com.example.fashion.RunnerTests',
  );
}
